runtime: nodejs20

automatic_scaling:
  max_instances: 1

handlers:
  # Serve angular files
  - url: /en/(.*\.js)
    static_files: browser/en/\1
    upload: browser/en/(.*\.js)
    mime_type: text/javascript
    secure: always
    redirect_http_response_code: 301

  - url: /es/(.*\.js)
    static_files: browser/es/\1
    upload: browser/es/(.*\.js)
    mime_type: text/javascript
    secure: always
    redirect_http_response_code: 301

  - url: /en/(.*\.css)
    static_files: browser/en/\1
    upload: browser/en/(.*\.css)
    mime_type: text/css
    secure: always
    redirect_http_response_code: 301

  - url: /es/(.*\.css)
    static_files: browser/es/\1
    upload: browser/es/(.*\.css)
    mime_type: text/css
    secure: always
    redirect_http_response_code: 301

  - url: /en/(.*\.txt)
    static_files: browser/en/\1
    upload: browser/en/(.*\.txt)
    mime_type: text/plain
    secure: always
    redirect_http_response_code: 301

  - url: /es/(.*\.txt)
    static_files: browser/\1
    upload: browser/es/(.*\.txt)
    mime_type: text/plain
    secure: always
    redirect_http_response_code: 301

  # Serve assets directly
  - url: /en/assets
    static_dir: browser/en/assets
    secure: always
    redirect_http_response_code: 301

  - url: /es/assets
    static_dir: browser/es/assets
    secure: always
    redirect_http_response_code: 301

  - url: /en/media
    static_dir: browser/en/media
    secure: always
    redirect_http_response_code: 301

  - url: /es/media
    static_dir: browser/es/media
    secure: always
    redirect_http_response_code: 301

  # Serve favicon directly
  - url: /favicon\.ico
    static_files: browser/en/assets/favicons/favicon.ico
    upload: browser/en/assets/favicons/favicon.ico
    secure: always
    redirect_http_response_code: 301

  # Serve legacy directly
  - url: /legacy.html
    static_files: browser/en/legacy.html
    upload: browser/en/legacy.html
    secure: always
    redirect_http_response_code: 301

  # Serve en
  - url: /en
    static_files: browser/en/index.html
    upload: browser/en/index.html
    secure: always
    redirect_http_response_code: 301

  - url: /en/.*
    static_files: browser/en/index.html
    upload: browser/en/index.html
    secure: always
    redirect_http_response_code: 301

  # Serve es
  - url: /es
    static_files: browser/es/index.html
    upload: browser/es/index.html
    secure: always
    redirect_http_response_code: 301

  - url: /es/.*
    static_files: browser/es/index.html
    upload: browser/es/index.html
    secure: always
    redirect_http_response_code: 301

  # Serve app TODO: this needs to redirect depending on browser language
  - url: /
    static_files: browser/en/index.html
    upload: browser/en/index.html
    secure: always
    redirect_http_response_code: 301
